// packages/angular_supabase_template/src/app/app.component.ts
import { Component } from '@angular/core';
import { createClient } from "@supabase/supabase-js";

@Component({
  selector: 'app-root',
  standalone: true,
  templateUrl: './app.component.html',
})
export class AppComponent {
  title = 'Hello, Angular with Supabase!';
  private _supabase = createClient('', '');
}

<h1>{{ title }}</h1>
<p><a href="/assets/auth.html">Open Supabase Auth UI</a></p>

// packages/react_supabase_template/src/App.tsx
import { createClient } from "@supabase/supabase-js";
import { useState } from "react";
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || "";
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "";
const _supabase = createClient(supabaseUrl, supabaseKey);
function App() {
  const [message] = useState("Hello, React with Supabase!");
  return (
    <div>
      <h1>{message}</h1>
      <p>
        <a href="/auth.html">Open Supabase Auth UI</a>
      </p>
    </div>
  );
}
export default App;
