// packages/react_postgres_template/src/App.tsx
import { createClient } from "@supabase/supabase-js";
import { useState } from "react";
const postgresUrl = import.meta.env.VITE_POSTGRES_URL || "";
const postgresKey = import.meta.env.VITE_POSTGRES_ANON_KEY || "";
const _postgres = createClient(postgresUrl, postgresKey);
function App() {
  const [message] = useState("Hello, React with Postgres!");
  return (
    <div>
      <h1>{message}</h1>
    </div>
  );
}
export default App;

// packages/vue_postgres_template/src/App.vue
<script setup lang="ts">
import { createClient } from "@supabase/supabase-js";
import { ref } from "vue";
const postgresUrl = import.meta.env.VITE_POSTGRES_URL || "";
const postgresKey = import.meta.env.VITE_POSTGRES_ANON_KEY || "";
const _postgres = createClient(postgresUrl, postgresKey);
const message = ref("Hello, Vue with Postgres!");
</script>
<template>
  <div>
    <h1>{{ message }}</h1>
  </div>
</template>
